### ISSUE TITLE
Default transform function cant handle circular dependencies

### ISSUE THREAD

**Issue by jescalan** [static-dev/spike-contentful#36]
So the contentful client resolves links and references is using proxies. So if you have a circular dependency of any length (ex. `post1` references `post2` references `post3` references `post1`), the transform function, which is recursive and causes getters to resolve by walking properties directly, will end in an infinite loop.

This is something of an edge case, but it has been reported twice already, and in addition to all the other drawbacks associated with the transform function leads me to believe that it should not be true by default, and instead should be false by default, or even extracted to a separate library entirely.

**Comment by liitfr** [comment]
Well I don't know if it can help but I had the same circular dependency context (blog posts can be related to 0..n other blog posts) 

I managed this recurcively in transformation :

```
self = module.exports =

  transformBlogPost: (e, explore = false) ->
    # Recursion management for related posts : get only first level
    if explore
      delete e.relatedBlogPosts

    # General cleansing content + enrichment, for exemple
    delete e.sys
    e.blogUrl = S(e.blogUrl).slugify().s
    e.pubDate = moment(e.lastUpdate,
    ['YYYY-MM-DD', 'DD/MM/YYYY']).format('DD/MM/YYYY')
    ...

    # Explore first level of related posts
    if not explore and e.hasOwnProperty('relatedBlogPosts')
      for relatedBlogPost in e.relatedBlogPosts
        # Cleansing
        delete relatedBlogPost.sys
        # Exploration
        self.transformBlogPost(relatedBlogPost.fields, true)

    e
```

It makes the job, but once again it was with root (i'm going to try it soon anyway with spike ;))

**Comment by jescalan** [comment]
Nice work! I do think ultimately we need to remove the transform function though to eliminate issues and edge cases. For now if you run into issues, just pass `transform: false` 😁

**Comment by liitfr** [comment]
I take up your suggestions ! It was a valuable tool to clean & enrich data models & json exports though

By the way Jeff, what was your motivation to change from export a json per model to export a global json ?
It was nice to $.get only relevant data. Not a big deal since it's still possible to create these files post-compile anyway.

Hope it doesn't bother you, don't know the best place to ask this related kind of questions. Maybe gitter ?

**Comment by jescalan** [comment]
Gitter is a good place for sure, the issues section I try to keep as bugs and problems 😁 

As for the global json, no particular reason, and would be happy to add an option for per-model export if someone wanted to work on a PR for it!

**Comment by jescalan** [comment]
Closed by the latest release 🎉
